name: 彩票推荐和开奖通知

on:
  schedule:
    # 每天中午12点运行推荐号码任务
    - cron: '0 4 * * *'  # UTC时间4点，对应北京时间12点
    # 每天晚上10点运行开奖查询任务
    - cron: '14 14 * * *'  # UTC时间14点14分，对应北京时间22点14分

jobs:
  lottery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv
          
      - name: 运行彩票脚本
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          if [ "${{ github.event.schedule }}" == "0 4 * * *" ]; then
            python scripts/lottery_recommendation.py
          else
            python scripts/lottery_check.py
          fi 